### ISSUE TITLE
Some comments and areas that could use clarification

### ISSUE THREAD

**Issue by christopher-dG** [invenia/BlueStyle#20]
Good on you guys for publishing this :+1: No idea how long it's been around but I'm just noticing it now with the badge.

Read through the guide and noticed a couple of things:

### Imports

Should there be any distinction between where imports come from? To illustrate, here's what I've taken to doing:

```jl
# Base and Core go first.
using Base: front
using Core: Builtin

# And then stdlibs.
using Dates: year

# And then external packages.
using Parameters: @with_kw
```

Not sure if that's something you want to look into, just putting in my 2c. 

### Keyword Arguments

There should probably be a case for keyword-only functions. Should I use `f(x=1, y=2)` or `f(; x=1, y=2)`? I always use the latter.

### Whitespace

Ranges: What about literals as offsets? e.g. should i use `xs[x:y-1]` or `xs[x : y - 1]`? I go with the former.

### NamedTuples

When there's only one element: `(; x=1)` or `(x=1,)`? I use the former, but I also like to always use the semicolon. `(x=1)` does not work, it parses to `x = 1`.

### Comments

> If your comment comment cannot be fitted inline then place the comment above the content to which it refers

Maybe there should be a note about sentence splitting here? I would write the example as:

```jl
# Number of nodes to predict. Again, an issue with the workflow order. 
# Should be updated after data is fetched.
p = 1
```

### Documentation

I think this discussion has been had before but I forget the outcome. Is one sentence per line okay? In the first example, I would have split the line after the first sentence, kind of like what I said about comments too. I'd rather have overlong lines for docstrings than lines that only contain a really long URL, personally. When it makes sense, I also split lines on commas if things get really long.

---

This has been a bit of a brain dump. Some of it is just reflective of my own preferences, but some of it probably warrants clarification. Don't feel obligated to agree with my opinions :smile:

**Comment by nickrobinson251** [comment]
Thanks for this opening, Chris!

We have guidelines for most of these - can you suggest how best to clarify them?

### Imports
"Should there be any distinction between where imports come from?" **No.**
Module imports are alphabetical:

> A module import should only specify a single package per line. The lines should be ordered alphabetically by the package/module name (note: relative imports preceed absolute imports).

### Whitespace in ranges

**We need to clarify, and maybe reconsider the advice here.** Current advice implies prefer `xs[x : y - 1]` over `xs[x:y-1]`... but i'm not sure we actually follow that in practice. Perhaps worth reconsidering. Definitely worth clarifying with another example.

### NamedTuples with one element
**We need to decide and clarify.** For the multi-element case we recommend `xy = (x=1, y=2)`, so i suppose `(x=1,)` is most conistent with that... but for splatting we'd need the colon anyway `(; xs...)` _and_ it fits with our keyword advice: "When calling a function always separate your keyword arguments from your positional arguments with a semicolon This avoids mistakes in ambiguous cases (such as splatting a Dict)". 

### Newlines in comments 
"Maybe there should be a note about sentence splitting here?" **Yes, we should clarify.**
 Currently we say "Comments should be complete sentences.", we should update this to make explicit that moving to a newline for a new sentence is okay, but arbitrarily splitting sentences is not i.e. sentence that are longer than a single line wrap at 92 characters, do not wrap them earlier. 

### Newlines in Documentation
"Is one sentence per line okay?" **Depends (yes in markdown, no in `.jl`). We should clarify this.**
It depends on whether you're writing in a markdown file or not.
In markdown one sentence per line is good; e.g. if writing the Readme or index page of the hosted docs, then always write exactly one sentence per line (it makes diffs easier). 
In docstrings sentences should wrap at 92 chars, like code, becuase this is friendlier for users when reading in the REPL (e.g. via REPL help mode) and for developers (since the documentation is being written in the same ditor they write code, which is wrapped at 92 chars)

**Comment by nickrobinson251** [comment]
> No idea how long it's been around

A few days on open-source and on Github, but [you contributed to it a couple years ago](https://github.com/invenia/BlueStyle/commits?author=christopher-dG) 😆

**Comment by christopher-dG** [comment]
Heh, yeah open source is what I meant :sweat_smile:. Thanks for addressing each point with PRs! One note on docstring line length is that it actually makes no difference for the REPL help mode. Both of these render the same (no line breaks):

```jl
"""
a b c d e f g
"""
f(x) = 2x

"""
a
b
c
d
e
f
g
"""
f(x) = 2x
```

Regardless I'm fine with still limiting the length of docstrings to the same length as regular code.

**Comment by nickrobinson251** [comment]
I think all points have been addressed - reopen if we missed anything - thanks for the excellent issue!
